# Generated by Django 2.2.7 on 2019-12-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100, verbose_name='Produto')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Valor')),
                ('description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=11, verbose_name='Contato')),
                ('photo', models.ImageField(upload_to='classificados', verbose_name='Foto')),
                ('begin_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
    ]
