# Generated by Django 2.2.7 on 2019-12-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do cliente:')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF:')),
                ('rg', models.CharField(blank=True, max_length=8, null=True, verbose_name='RG:')),
                ('endereco', models.CharField(max_length=100, verbose_name='Endereço:')),
                ('bairro', models.CharField(max_length=100, verbose_name='Bairro:')),
                ('numero', models.CharField(blank=True, max_length=100, null=True, verbose_name='n°:')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade:')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado:')),
                ('telefone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Telefone:')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular:')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email:')),
                ('dt_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
        ),
    ]
